version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 2

  - package-ecosystem: terraform
    directory: /infra/terraform/bootstrap
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/New_York
    open-pull-requests-limit: 2

  - package-ecosystem: terraform
    directory: /infra/terraform/prod
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/New_York
    open-pull-requests-limit: 2
