backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/homepage/static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "location" # Used in routes, e.g., /admin/collections/blog
    label: "Location" # Used in the UI
    folder: "/homepage/content/locations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.simple}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter.
      - {label: "Location Name", name: "title", widget: "string"}
      - {label: "Short Name", name: "simple", widget: "string"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Image Credit", name: "image_credit", widget: "string", required: false}
      - {label: "Status", name: "status", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Bearing", name: "bearing", widget: "number", valueType: "float", required: false}
      - {label: "Map Longitude", name: "center_long", widget: "number", valueType: "float"}
      - {label: "Map Latitude", name: "center_lat", widget: "number", valueType: "float"}
      - {label: "Marker Longitude", name: "marker_long", widget: "number", valueType: "float", required: false}
      - {label: "Marker Latitude", name: "marker_lat", widget: "number", valueType: "float", required: false}
      - {label: "Pitch", name: "pitch", widget: "number", valueType: "float", required: false}
      - {label: "Speed", name: "speed", widget: "number", valueType: "float", required: false}
      - {label: "Zoom", name: "zoom", widget: "number", valueType: "float", required: false}
