const locationData = [ 
    {
      "title": "AACC, La Casa Cultural, NACC",
      "simple": "aacc_la_casa_cultural_nacc",
      "id": 3,
      "image": "/images/aacc_la_casa_cultural_nacc.jpg",
      "image_alt": null,
      "image_credit": "Kristina Kim / YDN",
      "status": null,
      "bearing": 0.01,
      "center": [-72.93152025944596, 41.30704189027759],
      "marker": [-72.931415, 41.306982],
      "pitch": 20,
      "speed": 0.3,
      "zoom": 18.92,
      "text": "The four cultural centers have distinct histories. But the three on High Street have particularly interrelated stories. The Asian American Cultural Center, or the AACC, was formed when Asian American students lobbied for this space in the fall of 1978, through a meeting with the Yale President that alumni recall fondly as \"Shoe Day.\" At the time, the Asian American Students\' Alliance had been meeting in an office in the basement of Bingham, and asked the President to meet with them there so they could show him how small it was. Before the meeting, all the students took their shoes off—a common cultural practice in Asian homes—and left them out in the hallway. When President A. Bartlett Giamatti came down to the Bingham basement, he was greeted by a sea of at least 100 shoes leading to the door of the small office. Within the year, the President [began meeting with students](https://downatyale.com/aacc-oral-histories-grant-din/) to create a new space.\n In 1981, the AACC was established in its current location, where for years it housed Asian American and Chicanx students together. In 1993, the top floor became the Native American Cultural Center. Four years later Chicanx students joined Puerto Rican students to officially form Casa Boricua next door. In 2002, Chicanx students joined Casa Boricua and the center was renamed and officially established as La Casa Cultural. The mural painted on the side wall of La Casa represents the merging of Chicanx and Puerto Rican identities. Native American and Asian American students continued to share the house at 295 Crown Street until 2013, when the Native American Cultural Center opened next door."
    },
    {
      "title": "Broadway (The Shops at Yale)",
      "simple": "broadway_the_shops_at_yale",
      "id": 1,
      "image": "/images/broadway_the_shops_at_yale.jpg",
      "image_alt": null,
      "image_credit": "Shutterstock",
      "status": null,
      "bearing": -9.600000000000023,
      "center": [-72.93005897478628, 41.31140479609209],
      "marker": [-72.930126, 41.311541],
      "pitch": 40,
      "speed": 0.1,
      "zoom": 17.659071484622068,
      "text": "The Broadway you see now, lined with high-end, name brand retail shops, is a result of Yale's Broadway Redevelopment Plan. Citing dirty, unsafe streets and outdated stores unsuited for its students, Yale started buying up the existing, locally-owned properties on Broadway in 1997. Today, Yale carefully manages the entire street under \"The Shops at Yale,\" which also includes stores on Chapel Street. Even though Yale owns all of this real estate in New Haven, they do not pay taxes on most of their properties because of a Connecticut law that exempts most educational institutions from having to pay city or state taxes. In lieu of taxes, Yale gives a voluntary annual contribution of $11.5 million to the city, a figure [hundreds of millions of dollars](https://www.newhavenindependent.org/index.php/archives/entry/elicker_gov/) less than what Yale and Yale-New Haven hospital would pay in taxes based on the appraised worth of their tax-exempt properties."
    },
    {
      "title": "Cross Campus",
      "simple": "cross_campus",
      "id": 7,
      "image": "/images/cross_campus.jpg",
      "image_alt": null,
      "image_credit": "Alex Zhang / YDN",
      "status": null,
      "bearing": -61.60000000000003,
      "center": [-72.9274829694881, 41.310588554014174],
      "marker": [-72.927647, 41.310691],
      "pitch": 20,
      "speed": 0.23,
      "zoom": 17.8,
      "text": "On November 10, 2015, students of color and their allies under the umbrella name \"Next Yale\" held the March of Resilience, which gathered over 1,000 students on Cross Campus to demand the Yale administration take action to address a number of recent racist incidents on campus (see: SAE Fraternity, Grace Hopper College). In addition to ongoing discussion regarding the potential renaming of Calhoun College, students demanded recourse regarding [an email](https://medium.com/@denrsch/what-s-going-on-at-yale-a-reading-list-b9031ec8bd43) sent out of Assistant Head of College Erica Christakis which told students to \"look away\" if they saw offensive Halloween costumes. Next Yale presented six demands, including that Calhoun College be renamed, the two new colleges be named after women of color, and the promotion of the program in Ethnicity, Race, & Migration to departmental status. The students in Next Yale also explicitly linked [their demands](https://downatyale.com/nextyale-demands-for-the-administration/) to demands made by Black students at Yale in the 1960s, evincing the clear connections between different decades of Yale students of color.\nA few of their demands were met; one of the new colleges was named after Pauli Murray, a Black genderqueer activist and promiment civil rights lawyer. However, most were not. Ethnicity, Race, & Migration continued to struggle with hiring and retaining faculty, and in March 2019, all 13 tenured faculty members publicly withdrew their labor from the program in protest of unsustainable conditions. A student group called the Coalition for Ethnic Studies [emerged in response](https://yaledailynews.com/blog/2019/04/02/students-organize-to-support-erm-professors-withdrawal/) and held an Ethnic Studies Pop-Up Library on Cross Campus."
    },
    {
      "title": "Grace Hopper",
      "simple": "grace_hopper",
      "id": 5,
      "image": "/images/grace_hopper.jpg",
      "image_alt": null,
      "image_credit": "Surbhi Bharadwaj / YDN",
      "status": null,
      "bearing": 172,
      "center": [-72.9271882686457, 41.31003332154904],
      "marker": [-72.927177, 41.309967],
      "pitch": 40,
      "speed": 0.13,
      "zoom": 18.37184040845532,
      "text": "Above the entrance to the college office is an etching of Grace Hopper College\'s former namesake, John C. Calhoun. Calhoun was a Yale alum from South Carolina, one of the 19th century's foremost white supremacists and a politican who advocated for slavery as a \"positive good.\" In 2017, Yale changed the name to Grace Hopper College after years of activism from students, workers, and New Haven residents. The movement to rename Calhoun revitalized in 2015, in the wake of protests in Ferguson, Missouri and concurrent movements at Yale. Black students at Yale led the campaign to rename Calhoun, with key support from various community groups including New Haven immigrants rights\' activists from Unidad Latina en Acción (ULA). \nA critical moment in the movement occurred in July 2016, when a dining hall worker named Corey Menafee used a broomstick to smash a stained glass window inside the Calhoun dining hall that depicted two slaves carrying bales of cotton. In [an interview](https://www.democracynow.org/2016/7/15/exclusive_meet_yale_dishwasher_corey_menafee), Menafee explained why he smashed the window, saying, \"something inside me said, you know, that thing has to come down...as soon as you look at it, it just hurts. You feel it in your heart, like, oh, man… we shouldn\'t have to be subjected to those primitive and degrading images.\" \nYale pressured Menafee to resign and pressed charges against him for destruction of property. In the weeks following, the story made national news. Many students and faculty at Yale spoke out in Menafee\'s support. With backing from Yale\'s powerful blue-collar union, Local 35, Menafee was eventually hired back and the university dropped charges against him. Corey Menafee now works in the Morse-Stiles dining hall."
    },
    {
      "title": "New Haven Green / Phelps Gate",
      "simple": "new_haven_green_phelps_gate",
      "id": 4,
      "image": "/images/new_haven_green_phelps_gate.jpg",
      "image_alt": null,
      "image_credit": "Nancy Kennedy / Getty Images",
      "status": null,
      "bearing": 172,
      "center": [-72.9280551271001, 41.30847355141913],
      "marker": [-72.927987, 41.308345],
      "pitch": null,
      "speed": 0.25,
      "zoom": 17.372117891276627,
      "text": "College Street functions as an unofficial border between Yale\'s campus and New Haven. Though Yale is obviously located within New Haven, there are clear and distinct boundaries created institutionally, structurally, and architecturally by the university. Standing here, you actually can see that Phelps Gate has been intentionally misaligned with the central pathway of New Haven Green. If you have already been to campus, think of when many of you walked through Phelps Gate into Old Campus, a private, enclosed quad located in the middle of downtown New Haven. Though you may have been welcomed through these gates, who are these gates keeping out? \nThere was one critical time in Yale\'s history when the gates between Yale and the Green were opened. May Day, 1970. When President Brewster declared that the gates be kept open to the tens of thousands Black Panthers and supporters flowing into the city, Old Campus held portable toilets, functioning as a rest stop for those rallying on the Green. Two residential colleges, Pierson and Davenport, became a first aid and family and child day-care centers, respectively. May Day may have been one of the few times the university has suspended its normal campus-city boundaries."
    },
    {
      "title": "SAE Fraternity",
      "simple": "sae_fraternity",
      "id": 6,
      "image": "/images/sae_fraternity.jpg",
      "image_alt": null,
      "image_credit": "Ken Yanagisawa / YDN",
      "status": null,
      "bearing": 119.43790919956723,
      "center": [-72.93071060824661, 41.3072269598124],
      "marker": [-72.930670, 41.307210],
      "pitch": 20,
      "speed": 0.25,
      "zoom": 19.097093642073602,
      "text": "In the fall of 2015, Sigma Alpha Epsilon (SAE) [held a Halloween party](https://www.washingtonpost.com/news/grade-point/wp/2015/11/02/students-accuse-yale-sae-fraternity-brothers-of-having-a-white-girls-only-policy-at-their-party/) during which members of the fraternity stood outside the door chanting \"white girls only\" and letting only blonde women inside. The Halloween party was one of several incidents in the fall of 2015 that culminated in a widespread student movement against institutional racism at Yale. (See: Grace Hopper, Cross Campus)"
    },
    {
      "title": "Stiles",
      "simple": "stiles",
      "id": 0,
      "image": "/images/stiles.jpg",
      "image_alt": null,
      "image_credit": "Stephen Pitti",
      "status": null,
      "bearing": 167.2,
      "center": [-72.93093037800622, 41.31259267608269],
      "marker": [-72.930883, 41.312457],
      "pitch": 0,
      "speed": 0.3,
      "zoom": 17.92871709767812,
      "text": "This plaque, installed in the Ezra Stiles common room in 2016, was written by then-Head of College Stephen Pitti, Professor of History, American Studies, and Ethnicity, Race & Migration. Ezra Stiles is not the only space with evidence of Yale\'s colonial origins, but it is a unique instance where these origins have been made visible, thanks to Professor Pitti. In many cases, Yale\'s colonial past has been concealed, either intentionally or incidentally. \nWhat does it mean to walk into a college named after Ezra Stiles and also acknowledge and remember the slaves and servants he owned: Newport, Jacob, and Aaron?"
    },          
    {
      "title": "The House",
      "simple": "the_house",
      "id": 2,
      "image": "/images/the_house.jpg",
      "image_alt": null,
      "image_credit": "Irene Jiang / YDN",
      "status": null,
      "bearing": 155.20000000000005,
      "center": [-72.9329127653582, 41.30944976850142],
      "marker": [-72.932876, 41.309407],
      "pitch": null,
      "speed": 0.3,
      "zoom": 18.99,
      "text": "The Afro American Cultural Center, colloquially known as [\"The House,\"](https://afam.yalecollege.yale.edu/about-house/history) is the first of the four cultural centers we have here at Yale. Established in 1969 as \"Afro-America,\" the House was born out of the efforts of the Black Students Alliance at Yale (BSAY). After the House moved from its original Chapel Street location to its current home here, the center became a hub for organizers during the New Haven Black Panther Trials in 1970, when Black Panther co-founder Bobby Seale and eight other defendants were accused of the murder of suspected FBI informant Alex Rackley. Yale students housed visiting Black Panthers throughout the Trials, and students and faculty called for a strike—a suspension of academic priorities—so they could support local activism. The President at the time, Kingman Brewster, Jr., agreed, declaring famously that he himself was \"skeptical of the ability of black revolutionaries to achieve a fair trial anywhere in the United States.\" The President also kept Yale\'s gates open [throughout the Trials](https://news.yale.edu/2018/06/13/yale-panelists-recall-may-day-rally-transformed-campus-and-history) to the over 40,000 protesters who converged in the city. The Trials were a historical moment in which political power was built through shared struggles and collaborations between Black Yale students, Black New Haven residents, and Black Americans at large."
    },   
    {
      "title": "Yale Police Department",
      "simple": "yale_police_department",
      "id": 8,
      "image": "/images/yale_police_department.jpg",
      "image_alt": null,
      "image_credit": "Christian Abraham / Hearst CT Media",
      "status": null,
      "bearing": -61.6,
      "center": [-72.9286395105106, 41.31587850147989],
      "marker": [-72.928712, 41.315918],
      "pitch": 20,
      "speed": 0.4,
      "zoom": 18.39,
      "text": "In April of 2019, Hamden police officer Devin Eaton and Yale police officer Terrance Pollack shot twelve bullets at Stephanie Washington and Paul Witherspoon, two Black New Haven residents who had been sitting, unarmed, in their car. The shooting sparked the creation of the [Black Students for Disarmament at Yale](https://www.defundypd.com) (BSDY). \"We are a group of undergraduate students who, in the late hours following a 7+ hour rally on Thursday April 19, 2019, deemed it necessary to take a strong stance alongside New Haven in its fight for justice for Stephanie Washington and Paul Witherspoon,\" BSDY\'s website states. \nThe Yale Police Department (YPD) has a long history of racist assaults against Black students and New Haven residents. BSDY has released a zine detailing a number of them, including a 2015 incident when the YPD held Tahj Blow, a Black undergraduate student at the time, at gunpoint while he was unarmed and jogging from Sterling Memorial Library to his dorm room. Tahj's father, the *New York Times* columnist Charles Blow, [wrote about the incident](https://www.nytimes.com/2015/01/26/opinion/charles-blow-at-yale-the-police-detained-my-son.html), inspiring public outrage over the incident.\n In the wake of George Floyd\'s murder, BSDY has continued to advocate for the disarmament and eventual dismantling of the YPD."
  }
]

export default locationData
