name: Application

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  verify:
    name: Bun verify
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/application.yml@625efd11af9fd3b7f4d0ca972475173d5b25a472
