name: Application

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  verify:
    name: Bun verify
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/application.yml@ddaa918319be123c780876d510efb4715c1f879d
