name: Update Bun dependencies

on:
  schedule:
    - cron: "23 13 * * 2"
  workflow_dispatch:

permissions: {}

jobs:
  propose:
    permissions:
      contents: write
      pull-requests: write
    uses: collinbentley1/platform/.github/workflows/bun-dependency-update.yml@72fc2e8c48a07a106cfd040908f5dded2e958e43
