name: Infrastructure

on:
  pull_request:

permissions: {}

jobs:
  infrastructure:
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/infrastructure.yml@823466fd2920a1539f5337409c6b59da34700e8d
