name: Socket Firewall

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  firewall:
    name: Socket Firewall
    permissions:
      contents: read
    uses: collinbentley1/platform/.github/workflows/socket-firewall.yml@234fe5058348b7873476a8f6ce5a4ca966ea71d4
