name: Socket Firewall

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  firewall:
    name: Socket Firewall
    permissions:
      checks: read # Verify the exact successful checks from Socket App 156372.
      contents: read
    uses: collinbentley1/platform/.github/workflows/socket-firewall.yml@ddaa918319be123c780876d510efb4715c1f879d
