name: Socket Firewall

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  firewall:
    name: Socket Firewall
    permissions:
      checks: read # Verify the exact successful checks from Socket App 156372.
      contents: read
    uses: collinbentley1/platform/.github/workflows/socket-firewall.yml@87de70d83f389df661eaa7f3b8a4faa049f59f09
